services:
  - type: web
    name: e-learning-backend
    runtime: docker
    repo: https://github.com/Sadguru2004/e-learning-platform
    branch: main
    rootDir: Backend/e-learning
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:mysql://sql.freedb.tech:3306/freedb_ZmeeXLyE?useSSL=true
      - key: DB_USERNAME
        value: u_Qv30sn
      - key: DB_PASSWORD
        value: KZWPKdN7K7Wx
      - key: SPRING_PROFILES_ACTIVE
        value: production